### ISSUE TITLE
Integrate the thread from Discuss

### ISSUE THREAD

**Issue by openp2pdesign** [fablaborg/demo#4]
Please embed the thread on Discuss, this code should work:

```
<div id='discourse-comments'></div>

<script type="text/javascript">
  DiscourseEmbed = { discourseUrl: 'http://discuss.fablabs.io/',
                     discourseEmbedUrl: 'https://discuss.fablabs.io/t/curating-fablabs-org/4186/1' };

  (function() {
    var d = document.createElement('script'); d.type = 'text/javascript'; d.async = true;
    d.src = DiscourseEmbed.discourseUrl + 'javascripts/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(d);
  })();
</script>
```

More information [here](https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963).

**Comment by ghost** [comment]
Hello there, @mqvlm @openp2pdesign ... any progress on this?

**Comment by ghost** [comment]
Hi Massimo

I suppose that you need to configure github to serve the site under http://fablab.org and http://www.fablab.org

I'm getting a 404 from github if I point them to the github repo (set up for http://www.fablab.org now)

/ Peter

**Comment by openp2pdesign** [comment]
Yes, @trox are we ready to leave the beta and go public?

**Comment by openp2pdesign** [comment]
@trox I moved the content from beta.fablab.org to fablab.org
